[build.environment]
  NODE_VERSION = "20"

[build]
  publish = "dist"
  command = "pnpm build"

[[redirects]]
  from = "/nav"
  to = "/"
  status = 301

[[redirects]]
  from = "/nav/"
  to = "/"
  status = 301
